version: '2'
services:

  influxdb:
    image: ${PROJ_NAME}/influxdb:${TAG}
    container_name: influxdb
    mem_limit: 2G
    restart: unless-stopped
# Internal ports to be exposed to other linked services
# They will not be exposed to the host machine
#    expose:
#      - 8086
#      - 8083
#      - 2003
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - perf_analyzer
    volumes:
      - ./influx-database:/var/lib/influxdb

  grafana:
    image: ${PROJ_NAME}/grafana:${TAG}
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - perf_analyzer

networks:
  perf_analyzer:

volumes:
  grafana_data:
