- name: Get influxdb datasource
  uri:
    url: "http://grafana:3000/api/datasources/id/WSP"
    method: GET
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    status_code: 404,200
    headers:
      Accept: "application/json"
  register: resp

- name: Define influxdb datasource
  uri:
    url: "http://grafana:3000/api/datasources"
    method: POST
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    body: "{{ lookup('file', 'datastore.json') | from_json }}"
    status_code: 200
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
  when: resp.status == 404
