---
- hosts: localhost
  connection: local
  vars:
    grafana_username: admin
    grafana_password: admin
  tasks:
    - include_tasks: tasks/grafana.yml
    - include_tasks: tasks/dashboard_import.yml